library(dplyr)
library(Hmisc)
library(wesanderson)
library(extrafont)
library(ggplot2)
font_import()
#Season stats from 2011 to 2016
seasStats11.16 <- read.csv("~/Documents/sportsblog/1617/seasStats11-16.csv")
str(seasStats11.16)
seasStats11.16$pct2p <- as.numeric(seasStats11.16$pct2p)
seasStats11.16$pct3p <- as.numeric(seasStats11.16$pct3p)
seasStats11.16$att3p <- as.numeric(seasStats11.16$att3p)
seasStats11.16$ftr <- as.numeric(seasStats11.16$ftr)
seasStats11.16$pct2p <- seasStats11.16$m2p/ seasStats11.16$a2p
seasStats11.16$pct3p <- seasStats11.16$m3p/ seasStats11.16$a3p
seasStats11.16$att3p <- seasStats11.16$a3p/ seasStats11.16$fga
seasStats11.16$ftr <- seasStats11.16$fta/ seasStats11.16$fga
seasStats11.16$class <- factor(seasStats11.16$class, levels = c("FR", "SO", "JR", "SR"))
seasats <- seasStats11.16 %>% filter(totmin > 99)
length(which(seasStats11.16$a3p < 2))
length(which(seasStats11.16$a3p < .5))
seasats <- seasats %>% filter(mp > 4.9)
ggplot(seasats, aes(x = pct2p, y = pct3p)) + geom_point() + facet_wrap(~class)
seasats <- seasats %>% filter(mp > 9.9)
seasats %>% group_by(class) %>% summarize(mean(na.omit((pct3p)))
seasats %>% group_by(class) %>% summarize(mean(na.omit((pct3p))))
seasats %>% group_by(class) %>% summarize(median(na.omit((pct3p))))
seasats %>% group_by(class) %>% summarize(median(na.omit((pct2p))))
seasats %>% group_by(class) %>% summarize(mean(na.omit((pct2p))))
seasats <- seasats %>% filter(pos == 'G')
seasats <- seasStats11.16 %>% filter(mp > 4.9 & totmin > 99)
seasatsG <- seasats %>% filter(pos == 'G')
musslike <- seasatsG %>% filter(att3p >.45 & ftr <.40)
musslikeFR <- musslike %>% filter(class == "FR")
seasStats11.16 <- seasStats11.16 %>% mutate(fls40 = (pf*40)/mp)
fouryrpalette <- c("#ffbe4f","#6bd2db", "#0c457d", "#e8702a")
foulingstealing <- ggplot(seasStats11.16, aes(x = stlpct, y = fls40, color = class)) + geom_point() + theme_bw(base_family = "Liberation Sans") + scale_color_manual(values = fouryrpalette)
foulingblocking <- ggplot(seasStats11.16, aes(x = blkpct, y = fls40, color = class)) + geom_point() + theme_bw(base_family = "Liberation Sans") + scale_color_manual(values = fouryrpalette)
foulingblockingSJU <- ggplot((filter(seasStats11.16, school == "St. John's (NY)")), aes(x = blkpct, y = fls40, color = class, label = player)) + geom_point() + theme_bw(base_family = "Liberation Sans") + scale_color_manual(values = fouryrpalette) + geom_text(size = 3, vjust = -1.5, hjust = 0)
foulingblockingSJU

